blog/urls.py
from django.urls import path, include
from django.views.generic import TemplateView
from django.contrib.auth.views import LogoutView
from . import views

urlpatterns = [

	path('', views.showblog, name='showblog'),
	path('<int:post_id>/', views.specific_post, name='specific_post'),
	# path("register", views.register, name="register"),
	path('register/', TemplateView.as_view(template_name="account/base.html")),
    path('accounts/', include('allauth.urls')),
    path("logout/", LogoutView.as_view(), name="logout"),
    path('social-auth/', include('social_django.urls', namespace="social")),
    # path('logout', LogoutView.as_view()), где логинишься
]

board/urls.py
from django.urls import path, include
from . import views

app_name = "board"
urlpatterns = [	
	path('', views.IndexView.as_view(), name='index'),
	path('master/<int:pk>/', views.MasterDetailView.as_view(), name='master_detail'),
	path('customer/<int:pk>/', views.CustomerDetailView.as_view(), name='customer_detail'),
	path('customer/<int:pk>/edit', views.CustomerUpdateView.as_view(), name='customer_update'),
	path('customer/create', views.CustomerCreateView.as_view(), name='customer_create'),
	path('customer/<int:pk>/delete', views.CustomerDeleteView.as_view(), name='customer_delete'),	
]

myawesomeblog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
import events.views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', events.views.home, name='home'),
    path('posts/', include('blog.urls')),
    path('board/', include('board.urls')),
    path('service/', include('services.urls')),
    # path('accounts/', include('allauth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

board/models.py
from django.db import models

# Create your models here.
class Master(models.Model):
	master_name = models.CharField(max_length=30)
	registration_date = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return self.master_name
		

class  Customer(models.Model):
	master = models.ForeignKey(Master, on_delete=models.CASCADE)
	customer_name = models.CharField(max_length=30)
	registration_date = models.DateTimeField(auto_now_add=True)
	waiting_status = models.BooleanField(default=True)
	email = models.EmailField(default=None)
	comment = models.CharField(max_length=2000, default=None,  blank=True)

	def __str__(self):
		return self.customer_name

	@property
	def is_waiting(self):
		return bool(self.waiting_status)
		

board/forms.py
from django import forms
from .models import Master, Customer

class MasterForm(forms.ModelForm):
	class Meta:
		model = Master
		fields = "__all__"


class CustomerForm(forms.ModelForm):
	class Meta:
		model = Customer
		fields = "__all__"

board/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Master, Customer
# from .forms import MasterForm, CustomerForm

from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
# Create your views here.

class IndexView(ListView):
	template_name = "board/index.html"
	context_object_name = "customer_list"

	def get_queryset(self):
		return Customer.objects.filter(waiting_status=True)

class CustomerCreateView(CreateView):
	model = Customer
	fields = ["master","customer_name"]
	success_url = reverse_lazy("board:index")

class CustomerDetailView(DetailView):
	template_name = "board/customer_detail.html"
	model = Customer

class CustomerUpdateView(UpdateView):
	model = Customer
	fields = ["customer_name","email", "waiting_status"]
	template_name_suffix = "_update_form"
	success_url = reverse_lazy("board:index")

	def waiting_set(self):
		qs = super(CustomerUpdateView, self).get_queryset
		return qs.filter(owner=self.request.user)

class CustomerDeleteView(DeleteView):
	model = Customer
	success_url = reverse_lazy("board:index")

	# def get_queryset(self):
	# 	qs = super(CustomerDeleteView, self).get_queryset()
	# 	return qs.filter(owner=self.request.user)

	

class MasterDetailView(DetailView):
	template_name = "board/master_detail.html"
	model = Master

board/templates/board/base.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Приложение для записей мастера</title>
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
	<link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}"> 
</head>
<body>
	<nav class="navbar navbar-light bg-light">
		<a class="navbar-brand" href=" {% url 'board:index' %} ">
			Приложение для записей мастера123
		</a>
	</nav>
	{% block content %}
	{% endblock %}

	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>
</body>
</html>

board/templates/board/customer_confirm_delete.html
{% extends 'blog/base.html' %}
{% load static %}
{% block content %}
	<div class="conainer-fluid">
		<div class="row"></div>
		<br>
		<div class="row">
			<div class="col-md-2 col-xs-2 col-sm-2"></div>
			<div class="col-md-10 col-xs-10 col-sm-10">
				<form method="post"> {% csrf_token %}
					<div class="form-row">
						<div class="alert alert-warning">
							Вы уверены, что хотите удалить этого клиента? {{ object }}
						</div>
					</div>
					<button type="submit" class="btn btn-danger">
						<i class="fas fa-trash-alt"></i>
					</button>
				</form>
			</div>
		</div>
	</div>
	
{%endblock%}

board/templates/board/customer_detail.html
{% extends 'blog/base.html' %}
{% load static %}
{% block content %}
<div class="row">
	<div class="col-md-1 col-xs-1 col-sm-1"></div>
	<div class="col-md-10 col-xs-10 col-sm-10 text-center">
		<h3 class="round3" style="text-align:center;"> {{ customer }} </h3>
	</div>
	<div class="col-md-1 col-xs-1 col-sm-1"></div>
</div>
<div class="row">
	<div class="col-md-12 col-xs-12 col-sm-12 text-center">
		Это страница клиента
		<br>
		Имя мастера: {{ customer.customer_name }}
	</div>  
</div>
<br />
{% endblock %}

board/templates/board/customer_update_form.html
{% extends 'blog/base.html' %}
{% load static %}
{% block content %}
	<form method="post"> {% csrf_token %}
		{{ form.as_p }}
		<input type="submit" value="Update">
	</form>
	
{%endblock%}

board/templates/board/index.html
{% extends 'blog/base.html' %}
{% block content %}



<div class="container-fluid nounderline">
	<div class="row">
		<div class="col-md-1 col-xs-1 col-sm-1"></div>
		<div class="col-md-10 col-xs-10 col-sm-10">
			<h3 class="round3" style="text-align:xenter;">Клиенты</h3>
		</div>
		<div class="col-md-1 col-xs-1 col-sm-1"></div>
	</div>	
	<div class="row">
		<div class="col-md-10 col-xs-10 col-sm-10"></div>
		<div class="col-md-2 col-xs-1 col-sm-1">
			<a href="{% url 'board:customer_create' %}">						
				<button type="button" class="btn btn-primary">
					<i class="fas fa-plus"></i>
				</button>
			</a>			
			<br />
		</div>
	</div>
	<br />

	{% if customer_list %}
		{% for customer in customer_list %}
		<div class="row ">
			<div class="col-md-1 col-xs-1 col-sm-1"></div>
			<div class="col-md-7 col-xs-7 col-sm-7">
				<ul class="list-group">
					<li class="list-group-item ">
						<h3>
							<a class="nounderline" href="{% url 'board:customer_detail' customer.pk %}"> {{ customer.customer_name }} </a> 
							<span></span>
						</h3>
						<br>
						{{ customer.registration_date }}
						<div>
							Мастер <a href="{% url 'board:master_detail' customer.master.pk %}"> {{ customer.master }} </a>
						</div>
						<div>
							email: {{ customer.email|default_if_none:"Не заполнено" }}
							<br>
							Комментарий: {{ customer.comment|default_if_none:"Не заполнено" }}
						</div>						
					</li>
				</ul>
				<br >
			</div>
			<div class="col-md-1 col-xs-1 col-sm-1">
				<a href="{% url 'board:index' %}">
					<button type="button" class="btn btn-success">
						<i class="fas fa-check"></i>
					</button>
				</a>
			</div>
			<div class="col-md-1">
				<a href="{% url 'board:customer_update' customer.pk %}">
					<button type="button" class="btn btn-primary">
						<i class="fas fa-pen"></i>
					</button>
				</a>
			</div>
			<!--<div class="col-md-1">
				<a href="{% url 'board:customer_delete' customer.pk %}">
					<button type="button" class="btn btn-danger">
						<i class="fas fa-trash-alt"></i>
					</button>
				</a>
			</div> -->
			<div class="col-md-1">
				<a href="#">
					<button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#exampleModal">
						<i class="fas fa-trash-alt"></i>
					</button>

					<form  method="POST" action="{% url 'board:customer_delete' customer.pk %}">
						<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
						  <div class="modal-dialog">
						    <div class="modal-content">
						      <div class="modal-header">
						        <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
						        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
						      </div>
						      <div class="modal-body">
						        <p class="lead text-muted">Вы уверены, что хотите удалить {{ customer.customer_name }}?</p>
						      </div>
						      <div class="modal-footer">
						        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>	      
						        {% csrf_token %}<button type="submit" class="btn btn-primary">Save changes123 </button>							
						      </div>
						    </div>
						  </div>
						</div>
					</form>
				</a>
				
			</div>	
		</div>
		{% endfor %}
		{% endif %}
</div>
{% endblock %}

board/templates/board/master_detail.html
{% extends 'blog/base.html' %}
{% load static %}
{% block content %}
<div class="row">
	<div class="col-md-1 col-xs-1 col-sm-1"></div>
	<div class="col-md-10 col-xs-10 col-sm-10 text-center">
		<h3 class="round3" style="text-align:center;"> {{ master }} </h3>
	</div>
	<div class="col-md-1 col-xs-1 col-sm-1"></div>
</div>
<div class="row">
	<div class="col-md-12 col-xs-12 col-sm-12 text-center">
		Это страница первого мастера
		<br>
		Имя мастера: {{ master.master_name }}
	</div>  
</div>
<br />
{% endblock %}